### ISSUE TITLE
Create index

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/dime-data-handbook#78]
There are a few topics that will be mentioned in different chapters, and indexing them will help us keep track of that as we review the text.

**Comment by bbdaniels** [comment]
I thought I already had this set up... it was in early drafts of the PDF but it is not there anymore! Anyway the `index{}` command is used throughout and automatically populates this when it is done correctly.

**Comment by kbjarkefur** [comment]
I found that more people had issues with `makeidx` package, so someone had written a wrapper for that package called `imakeidx` that we are now using and works better.

**Comment by kbjarkefur** [comment]
`\index{}` is creating an extra space in the text. We (i.e myself) should fix that!

**Comment by kbjarkefur** [comment]
It is not `\index{}` that create the extra spaces, it is `\sidenote{}`. But it is not consistently an extra space.

**Comment by kbjarkefur** [comment]
it is `\index{}` and `\sidenote{}` in conjunction, and sometimes new line in text editor. To solve this try the following:

1. Since `\index{}` does not appear in the text, see if it can be moved so it is one word, or even a full stop removed from `\sidenote{}`. Obviously do not move it too far as we do not want the page references on the index page to be imprecise.
2. Make sure that some word or character follows on the same line as `\sidenote{}`, as in the closing bracket `}` in `\sidenote{}` is not the last character on that line in the text editor.

**Comment by bbdaniels** [comment]
Closing and moving to #476
